module.exports = {
    queues: {

        GENERATE_VIDEO_THUMBNAIL_QUEUE: 'GENERATE_VIDEO_THUMBNAIL_QUEUE',
        GENERATE_VIDEO_THUMBNAIL_FINISH: 'GENERATE_VIDEO_THUMBNAIL_FINISH',
        COMPRESS_VIDEO_FINISH: 'COMPRESS_VIDEO_FINISH',

        TRANSCRIBE_VIDEO_QUEUE: 'TRANSCRIBE_VIDEO_QUEUE',
        TRANSCRIBE_FINISH_QUEUE: 'TRANSCRIBE_FINISH_QUEUE',

        CONVERT_VIDEO_TO_ARTICLE_QUEUE: 'CONVERT_VIDEO_TO_ARTICLE_QUEUE',
        CONVERT_VIDEO_TO_ARTICLE_FINISH_QUEUE: 'CONVERT_VIDEO_TO_ARTICLE_FINISH_QUEUE',

        EXPORT_ARTICLE_TRANSLATION: `EXPORT_ARTICLE_TRANSLATION`,
        EXPORT_ARTICLE_TRANSLATION_PROGRESS: `EXPORT_ARTICLE_TRANSLATION_PROGRESS`,
        EXPORT_ARTICLE_TRANSLATION_FINISH: `EXPORT_ARTICLE_TRANSLATION_FINISH`,
        EXPORT_ARTICLE_TRANSLATION_COMPRESSION_FINISH: `EXPORT_ARTICLE_TRANSLATION_COMPRESSION_FINISH`,

        ARCHIVE_ARTICLE_TRANSLATION_AUDIOS: `ARCHIVE_ARTICLE_TRANSLATION_AUDIOS`,
        ARCHIVE_ARTICLE_TRANSLATION_AUDIOS_PROGRESS: `ARCHIVE_ARTICLE_TRANSLATION_AUDIOS_PROGRESS`,
        ARCHIVE_ARTICLE_TRANSLATION_AUDIOS_FINISH: `ARCHIVE_ARTICLE_TRANSLATION_AUDIOS_FINISH`,

        BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE: `BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE`,
        BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_PROGRESS: `BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_PROGRESS`,    
        BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_FINISH: `BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_FINISH`,    

        BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_AND_SIGNLANGUAGE: `BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_AND_SIGNLANGUAGE`,
        BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_AND_SIGNLANGUAGE_FINISH: `BURN_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_AND_SIGNLANGUAGE_FINISH`,
    
        GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE: `GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE`,
        GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_PROGRESS: `GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_PROGRESS`,
        GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_FINISH: `GENERATE_ARTICLE_TRANSLATION_VIDEO_SUBTITLE_FINISH`,

        UPDATE_ARTICLE_SLIDE_VIDEO_SLICE: 'UPDATE_ARTICLE_SLIDE_VIDEO_SLICE',
        UPDATE_ARTICLE_SLIDE_VIDEO_SLICE_FINISH: 'UPDATE_ARTICLE_SLIDE_VIDEO_SLICE_FINISH',
        UPDATE_ARTICLE_VIDEO_SPEED: 'UPDATE_ARTICLE_VIDEO_SPEED',
        UPDATE_ARTICLE_VIDEO_SPEED_FINISH: 'UPDATE_ARTICLE_VIDEO_SPEED_FINISH',
        UPDATE_ARTICLE_SLIDE_VIDEO_SPEED: 'UPDATE_ARTICLE_SLIDE_VIDEO_SPEED',
        UPDATE_ARTICLE_SLIDE_VIDEO_SPEED_FINISH: 'UPDATE_ARTICLE_SLIDE_VIDEO_SPEED_FINISH',

        EXPORT_IMAGE_TRANSLATION_QUEUE: `EXPORT_IMAGE_TRANSLATION_QUEUE`,
        EXPORT_IMAGE_TRANSLATION_FINISH_QUEUE: `EXPORT_IMAGE_TRANSLATION_FINISH_QUEUE`,
    }
}