FROM anuvaadio/node_ffmpeg:6
WORKDIR /exporter-service

COPY . .
RUN npm install

EXPOSE 4000
CMD ["npm", "run", "docker:dev"]
HEALTHCHECK --start-period=30s --interval=2m CMD wget --quiet --tries=1 localhost:4000/health  -O /dev/null || exit 1
